CREATE TABLE ads_basic_performance (
  ad_id STRING,
  add_to_cart INT,
  adset_id STRING,
  campaign_id STRING,
  channel STRING,
  clicks INT,
  comments INT,
  creative_id STRING,
  date DATE,
  engagements INT,
  impressions INT,
  installs INT,
  likes INT,
  link_clicks INT,
  placement_id STRING,
  post_click_conversions INT,
  post_view_conversions INT,
  posts INT,
  purchase INT,
  registrations INT,
  revenue INT,
  shares INT,
  spend INT,
  total_conversions INT,
  video_views INT
);
